### PR TITLE
Added support for linear and rgba patterns and right aligned text

### PR DESCRIPTION
**Pull request by crycode-de**
**Added support for linear and rgba patterns.**
Using patterns you can create gradients and semi transparent drawing.

**Added support for right aligned text.**

Examples are included/updated.

Also added TypeScript typings.

### CODE REVIEW

**Comment by vesteraas** [comment]
Thank you for your contribution!  I will have a look at your pull request as soon as possible.

**Comment by vesteraas** [comment]
Thank you for your contribution!  I will have a look at the pull request as soon as possible.

**Comment by vesteraas** [comment]
I've merged your pull request and published the changes.  I also added your name to the list of contributors.

**Comment by crycode-de** [comment]
Thank you very much :-)

**Pull request merged**
